int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int sqrt_help(int n, int sqrt);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int prime_num_helper(int n, int factor, int num_of_factor);
int is_palindrome(char *s);
int is_palindrome_helper(char *s1, char *s2);
char *mv_to_last_char(char *s);
